type MutationResponse {
    status: Int!
    message: String!
    token: String
    data: GlobalType
}

type permissionResponse {
    status: Int!
    message: String!
    data: GlobalType
}

## union types
union GlobalType = Staff | Branch | Transport | TransportPermission | StaffPermission